//#include Fighting/Tamer.js
//#include helpers/Magic.js
//#include Fighting/AutoTargetting.js
//#include Fighting/SpellWeaving.js
//#include Fighting/SpellWeaving.js
//#include Training/CombatTrain.js
//#include helpers/Target.js
//#include WIP/TestScripts.js
//#include Actions/Automated/ShortCuts.js
